services:
  angular-create:
    # user: "${UID:-1000}:${GID:-1000}"  # UID:GID of the host or created user
    image: node:current-alpine3.22
    working_dir: /app
    profiles: ["create"]
    volumes:
      - .:/app
    ports:
      - "${DEV_PORT:-4200}:4200"
    environment:
      - APP_NAME=my-angular-app
      - ANGULAR_CREATE_OPTIONS=--routing --style=scss --ssr
      - NODE_NO_WARNINGS=1
    command: >
      sh -c "
        npm install -g @angular/cli &&
        ng new ${APP_NAME} --skip-git --skip-install ${ANGULAR_CREATE_OPTIONS} &&
        rm -rf ${APP_NAME}/.gitignore &&
        mv ${APP_NAME}/README.md ${APP_NAME}/README-${APP_NAME}.md &&
        mv ${APP_NAME}/* . &&
        mv ${APP_NAME}/.* . 2>/dev/null || true &&
        rm -rf ${APP_NAME} &&
        npm i &&
        npm pkg set scripts.serve:ssr=\"npm run serve:ssr:${APP_NAME}\"
      "
  angular-dev:
    build: 
      context: .
      target: dev
    container_name: angular-app-dev
    ports:
      - "${DEV_PORT:-4200}:4200"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: sh -c "ng serve --host 0.0.0.0 --poll=1000"
    profiles: ["dev"]
  angular-prod:
    build: 
      context: .
      target: build
    container_name: angular_app_container
    ports:
      - "${PROD_PORT:-4000}:4000"
    profiles: ["build"]
  angular-prod-no-ssr:
    build: 
      context: .
      target: production-no-ssr
    container_name: angular_app_no_ssr_container
    ports:
      - "${PROD_PORT:-4000}:80"
    profiles: ["build-no-ssr"]
